import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderTop from "../components/HeaderTop";
import HeaderMain from "../components/HeaderMain";
import Navbar from "../components/Navbar";
import Mobnavbar from "../components/Mobnavbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
//import { SessionProvider } from "next-auth/react";
//import ClientProvider from "./ClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hulu School Tutoring Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ All components go inside the provider */}
        <HeaderTop />
        <HeaderMain />
        <Navbar />
        <Mobnavbar />
        {children}
      </body>
    </html>
  );
}
